server:
  port: 8080
logging:
  level:
    org:
      springframework: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
              
spring:
  messages:
    basename: messages
  thymeleaf:
    mode: HTML
